Fixed: when $SCALA_HOME is set to an uncompitable version, throws: java.lang.NoSuchMethodError: scala.tools.nsc.Global.log(Ljava/lang/Object;)V at scala.tools.selectivecps.SelectiveCPSPlugin.<init>(SelectiveCPSPlugin.scala:36) Caused: java.lang.reflect.InvocationTargetException at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39) at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27) at java.lang.reflect.Constructor.newInstance(Constructor.java:513) at scala.tools.nsc.plugins.Plugin$.instantiate(Plugin.scala:152) at scala.tools.nsc.plugins.Plugins$$anonfun$loadRoughPluginsList$1.apply(Plugins.scala:34) at scala.tools.nsc.plugins.Plugins$$anonfun$loadRoughPluginsList$1.apply(Plugins.scala:34) at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:194) at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:194) at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59) at scala.collection.immutable.List.foreach(List.scala:45) at scala.collection.TraversableLike$class.map(TraversableLike.scala:194) at scala.collection.immutable.List.map(List.scala:45) at scala.tools.nsc.plugins.Plugins$class.loadRoughPluginsList(Plugins.scala:34) at scala.tools.nsc.Global.loadRoughPluginsList(Global.scala:35) at scala.tools.nsc.plugins.Plugins$class.roughPluginsList(Plugins.scala:37) at scala.tools.nsc.Global.roughPluginsList(Global.scala:35) at scala.tools.nsc.plugins.Plugins$class.loadPlugins(Plugins.scala:73) at scala.tools.nsc.Global.loadPlugins(Global.scala:35) at scala.tools.nsc.plugins.Plugins$class.plugins(Plugins.scala:98) at scala.tools.nsc.Global.plugins(Global.scala:35) at scala.tools.nsc.plugins.Plugins$class.computePluginPhases(Plugins.scala:109) at scala.tools.nsc.Global.computePluginPhases(Global.scala:35) at scala.tools.nsc.Global.computePhaseDescriptors(Global.scala:596) at scala.tools.nsc.Global.phaseDescriptors(Global.scala:601) at scala.tools.nsc.Global$Run.<init>(Global.scala:703) at scala.tools.nsc.interactive.Global$TyperRun.<init>(Global.scala:927) at scala.tools.nsc.interactive.Global.newTyperRun(Global.scala:953) at scala.tools.nsc.interactive.Global.<init>(Global.scala:166) at org.netbeans.modules.scala.core.interactive.Global.<init>(Global.scala:20) at org.netbeans.modules.scala.core.ScalaGlobal.<init>(ScalaGlobal.scala:620) at org.netbeans.modules.scala.core.ScalaGlobal$.getGlobal(ScalaGlobal.scala:361) at org.netbeans.modules.scala.core.ScalaParserResult.<init>(ScalaParserResult.scala:67) at org.netbeans.modules.scala.core.ScalaParser.parse(ScalaParser.scala:85)